name: CI

on:
  push:
    tags:
      - 'v*'
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - run: pnpm install --frozen-lockfile
      - run: npx playwright install --with-deps

      - run: |
          pnpm run check
          npx nx run-many -t test build typecheck e2e

      - run: npx nx fix-ci
        if: always()
